name: groups_field
description: Group widgets by some attribute.
publish_to: "none"
version: 0.2.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  pedantic: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.0.0
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.15.2

flutter:
  uses-material-design: true
